### ISSUE TITLE
readme recommends hdl-dump old server. however, wLaunchELF 4.43x_isr_hdd can also inject hdd PATINFO header

### ISSUE THREAD

**Issue by israpps** [samicrusader/psx-osdsys#1]
https://github.com/samicrusader/psx-osdsys/blob/463828316e2c52a6e5ebbf0a9d1aa1b5d368ad84/README.md?plain=1#L21-L24

- [wLaunchELF 4.43x_isr_hdd](https://github.com/israpps/wLaunchELF_ISR_hdd)

The setup is simple

Under HDDManager, a new option called inject will appear. when called. it will open the chosen partition and attempt to inject the following files into their appropiate locations on the PATINFO HeaderÑ

- `system.cnf`
- `icon.sys`
- `list.ico`
- `boot.kelf`

these files will be loaded from
```cmd
mass:/__Headers/PARTITION_NAME/FILE
```

**Comment by samicrusader** [comment]
I haven't touched a PS2 in a hot minute so I ended up missing out on some of this stuff; lemme get some food and I'll test and add it in.

**Comment by samicrusader** [comment]
done: https://github.com/samicrusader/psx-osdsys/commit/d78a8628642f061fc41a64f840350650f3f28065
